from django.core.exceptions import ValidationError
import urllib

def valid_location:
